server:
  host: 0.0.0.0
  port: 3000
  cors:
    - "http://0.0.0.0:4200"
    - "http://127.0.0.1:4200"
    - "http://localhost:4200"
swagger:
  title: E-Reputation
  description: API de l'e-Reputation
  version: 1.0
  tag: E-Reputation
  path: documentation
mongodb:
  login: 'root'
  password: 'password'
  host: '0.0.0.0'
  port: '27017'
  database: 'digrep'
  uri_prefix: 'mongodb://'
  uri_suffix: '?authSource='
  authdb: 'admin'
